config/routes.rb
Rails.application.routes.draw do
  # Define your routes here
  get 'about', to: 'about#index', as: 'about'
  get 'contacts/new', to: 'contacts#new', as: 'new_contact'
  post 'contacts', to: 'contacts#create', as: 'create_contact'
  get 'home/index'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<script src="https://cdn.tailwindcss.com"></script>
<%= content_for :title, "Hakkımızda" %>

<body class="bg-green-600">
  <div class="container mx-auto">
    <h1 class="text-4xl font-bold text-white">Hakkımızda</h1>
    <p class="mt-4 text-lg text-white">Bu sayfa hakkımızda içeriği ile doldurulacak.....</p>
  </div>
</body>

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/new.html.erb
<script src="https://cdn.tailwindcss.com"></script>
<div class="container mx-auto mt-12 contact">
  <h1 class="mb-4 text-4xl font-bold">İletişim</h1>
  <%= form_with(url: '/contact_submit', method: 'post', class: 'max-w-md mx-auto') do |form| %>
    <div class="mb-4">
      <%= label_tag :name, 'İsim', class: 'block text-lg font-bold mb-2' %>
      <%= form.text_field :name, class: 'w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-green-500 text-black' %>
    </div>
    <div class="mb-4">
      <%= label_tag :email, 'E-posta', class: 'block text-lg font-bold mb-2' %>
      <%= form.email_field :email, class: 'w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-green-500 text-black' %>
    </div>
    <div class="mb-6">
      <%= label_tag :message, 'Mesaj', class: 'block text-lg font-bold mb-2' %>
      <%= form.text_area :message, class: 'w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-green-500 text-black' %>
    </div>
    <%= form.submit 'Gönder', class: 'bg-green-900 text-white px-6 py-3 rounded-lg shadow-md hover:bg-green-600 transition-colors duration-300' %>
  <% end %>
</div>

app/views/home/about.html.erb
<div class="container mx-auto mt-12 about">
  <h1 class="mb-4 text-4xl font-bold">Hakkımızda</h1>
  <p class="mb-4 text-lg">Mobil Uygulama Tanıtımı, en son teknolojilerle size hizmet vermektedir.</p>
  <p class="text-lg">Ekibimiz uzman ve deneyimlidir.</p>
</div>

app/views/home/contact.html.erb
<div class="container mx-auto mt-12 contact">
  <h1 class="mb-4 text-4xl font-bold">İletişim</h1>
  <%= form_with(url: '/contact_submit', method: 'post', class: 'max-w-md mx-auto') do |form| %>
    <div class="mb-4">
      <%= form.label :name, class: 'block text-lg font-bold mb-2' %>
      <%= form.text_field :name, class: 'w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-green-500' %>
    </div>
    <div class="mb-4">
      <%= form.label :email, class: 'block text-lg font-bold mb-2' %>
      <%= form.email_field :email, class: 'w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-green-500' %>
    </div>
    <div class="mb-6">
      <%= form.label :message, class: 'block text-lg font-bold mb-2' %>
      <%= form.text_area :message, class: 'w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-green-500' %>
    </div>
    <%= form.submit 'Gönder', class: 'bg-green-500 text-white px-6 py-3 rounded-lg shadow-md hover:bg-green-600 transition-colors duration-300' %>
  <% end %>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="tr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>WhatsApp Clone</title>
  <script src="https://cdn.tailwindcss.com"></script>

</head>
<body class="font-sans text-gray-900 bg-gray-100">
  <header class="p-4 bg-black">
    <div class="container mx-auto">
      <h1 class="text-2xl font-bold text-white"></h1>
  <div class="mb-4">
      <%= image_tag 'image4.png', alt: 'Image 4' %>
    </div>
      
    </div>
  </header>

  <main class="container p-4 mx-auto">
    <div class="mb-6 text-center">
      <h2 class="mb-2 text-3xl font-semibold text-gray-800">WhatsApp'ı İndir</h2>
      <p class="mb-4 text-lg text-gray-700">WhatsApp'ı indirerek, arkadaşlarınızla ve ailenizle iletişimde kalın.</p>
     
    </div>
    
    <div class="relative mb-8 image-container ">
      <%= image_tag 'image1.png', alt: 'Image 1', class: 'w-full rounded-2xl' %>
      <div class="absolute inset-0 flex flex-col items-center justify-center p-6 text-white bg-black bg-opacity-50 rounded-lg">
        <h1 class="mb-2 text-2xl font-semibold">Mesajlaşırken gizliliğinizi koruyun.</h1>
        <p class="mb-4"> Dünyanın her yerinde ücretsiz kullanılabilen basit, güvenilir, özel mesajlaşma ve arama.</p>
        <a href="https://www.whatsapp.com/download" class="px-4 py-2 text-white transition bg-green-600 rounded hover:bg-green-700">İndir</a>
      </div>
    </div>
  </main>
  
    <div class="flex items-center mb-8 image-container">
      <div class="flex-1">
        <%= image_tag 'image2.png', alt: 'Image 2' %>
      </div>
      <div class="flex-1 p-6 text-white bg-black bg-opacity-50 rounded-lg">
        <h1 class="mb-2 text-2xl font-semibold">Sesli ve görüntülü aramalarla hiçbir anı kaçırmayın.</h1>
        <p class="text-left"> Sesli ve görüntülü aramalar sayesinde, sınıf arkadaşlarınızla yapacağınız bir grup aramasından annenizle yapacağınız kısa bir görüşmeye kadar her durumda sanki aynı odadaymışsınız gibi hissedin.</p>
      </div>
    </div>

    <div class="flex items-center mb-8 image-container">
      <div class="flex-1">
        <%= image_tag 'image3.png', alt: 'Image 3' %>
      </div>
      <div class="flex-1 p-6 text-white bg-black bg-opacity-50 rounded-lg">
        <h1 class="mb-2 text-2xl font-semibold">Özgürce konuşun.</h1>
        <p class="text-left">Uçtan uca şifreleme sayesinde kişisel mesaj ve aramalarınız güvence altına alınır. Gönderilen içerikler yalnızca siz ve konuştuğunuz kişi tarafından okunabilir veya dinlenebilir. WhatsApp dahil olmak üzere aradaki hiç kimse okuyamaz veya dinleyemez.</p>
      </div>
    </div>
    
      <div class="flex justify-center ">
        <%= image_tag 'image5.png', alt: 'Image 5' %>
      </div>
    
 
<footer class="p-8 text-white bg-black">
    <div class="container mx-auto text-center">
      <div class="flex items-center mb-4">
        <%= image_tag 'image4.png', alt: 'Image 4' %>
      </div>
      <div class="mt-2 text-left">
        <a href="https://www.whatsapp.com/download" class="px-4 py-2 text-white transition bg-green-600 rounded hover:bg-green-700">İndir</a>
      </div>

      <div class="grid grid-cols-2 gap-4 mt-8">
        <div>
          <h3 class="text-lg font-semibold">Ne yapıyoruz?</h3>
          <ul>
            <li>Özellikler</li>
            <li>Blog</li>
            <li>Güvenlik</li>
            <li>İşletmeler İçin</li>
            <li>Biz kimiz?</li>
          </ul>
        </div>

        <div>
          <h3 class="text-lg font-semibold">Hakkımızda</h3>
          <ul>
            <li>Kariyer Olanakları</li>
            <li>Marka Merkezi</li>
            <li>Gizlilik</li>
          </ul>
        </div>

        <div>
          <h3 class="text-lg font-semibold">WhatsApp'ı kullanın</h3>
          <ul>
            <li>Android</li>
            <li>iPhone</li>
            <li>Mac/PC</li>
            <li>WhatsApp Web</li>
          </ul>
        </div>

        <div>
          <h3 class="text-lg font-semibold">Yardıma mı ihtiyacınız var?</h3>
          <ul>
            <li>Bizimle İletişime Geçin</li>
            <li>Yardım Merkezi</li>
            <li>İndir</li>
            <li>Güvenlik Tavsiyeleri</li>
          </ul>
        </div>
      </div>

      <p class="mt-8">2024 © WhatsApp LLC</p>
      <p>Koşullar ve Gizlilik İlkesi | Site haritası</p>
    </div>
  </footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mobil Uygulama Tanıtımı</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="font-sans text-white bg-green-500">
  <header class="p-4 bg-green-600">
    <nav class="container flex items-center justify-between mx-auto">
      <ul class="flex space-x-4">
  <li><%= link_to 'Ana Sayfa', root_path, class: 'text-white hover:text-gray-200' %></li>
  <li><%= link_to 'Hakkımızda', about_path, class: 'text-white hover:text-gray-200' %></li>
  <li><%= link_to 'İletişim', new_contact_path, class: 'text-white hover:text-gray-200' %></li>
</ul>

    </nav>
  </header>

  <div class="container mx-auto">
    <%= yield %>
  </div>

</body>
</html>